# Generated by Django 3.2.6 on 2021-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0002_linea_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_base',
            name='File_Id',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea_base',
            name='File_url',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea_base',
            name='Folder_id',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
