# Generated by Django 3.2.6 on 2021-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0004_temp_linea_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_linea_base',
            name='Usuario',
            field=models.CharField(default='user0', max_length=15),
        ),
    ]
