# Generated by Django 3.2.7 on 2021-09-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0006_auto_20210917_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_encuestas',
            old_name='Frecuecia',
            new_name='Frecuencia',
        ),
    ]
