# Generated by Django 3.1.13 on 2021-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0008_auto_20211225_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encuesta', models.IntegerField()),
                ('Encuestado', models.CharField(max_length=50)),
                ('Latitud', models.IntegerField()),
                ('Longitud', models.IntegerField()),
                ('Altitud', models.IntegerField()),
                ('Link_foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='datos_encuestas',
            name='Clase',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_encuestas',
            name='Label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_encuestas',
            name='Usuario',
            field=models.CharField(max_length=30),
        ),
    ]
