# Generated by Django 3.1.13 on 2021-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0009_auto_20211229_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='DNI_Encuestado',
            field=models.CharField(default=11, max_length=15),
            preserve_default=False,
        ),
    ]
