# Generated by Django 3.1.13 on 2021-12-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0010_coordenadas_dni_encuestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenadas',
            name='DNI_Encuestado',
        ),
    ]
