# Generated by Django 3.1.13 on 2021-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0011_remove_coordenadas_dni_encuestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='Diosesis',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='Estado_civil',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='Sexo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
