# Generated by Django 3.1.13 on 2021-12-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0012_auto_20211230_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='DNI_Encuestado',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
