# Generated by Django 3.1.13 on 2021-12-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0014_coordenadas_num_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='Geolocalizacion_acuracy',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
