# Generated by Django 3.1.13 on 2021-12-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0015_coordenadas_geolocalizacion_acuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas',
            name='Altitud',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='Latitud',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='coordenadas',
            name='Longitud',
            field=models.CharField(max_length=11),
        ),
    ]
