# Generated by Django 3.1.13 on 2022-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0017_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Search1',
        ),
    ]
