# Generated by Django 3.1.13 on 2022-01-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0018_auto_20220115_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search1',
        ),
    ]
