# Generated by Django 3.1.13 on 2022-04-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0019_delete_search1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_encuesta', models.IntegerField()),
                ('Numero_preg', models.IntegerField()),
                ('Pregunta', models.CharField(max_length=300)),
                ('Tipo_preg', models.IntegerField()),
                ('Columna', models.CharField(max_length=100)),
                ('Label', models.CharField(max_length=500)),
                ('Label_en_sheet', models.CharField(max_length=50)),
                ('Filas_preg_tipo_matriz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_encuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encuesta', models.CharField(max_length=100)),
                ('Sheet_Id', models.CharField(max_length=60)),
                ('Hoja', models.CharField(max_length=50)),
                ('Numero', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datos_encuestas',
            name='Clase',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datos_encuestas',
            name='Label',
            field=models.CharField(max_length=500),
        ),
    ]
