# Generated by Django 4.2 on 2023-04-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0022_alter_coordenadas_id_alter_datos_encuestas_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestas',
            name='Otros',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
