# Generated by Django 4.2 on 2023-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineaBase', '0023_encuestas_otros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas',
            name='Altitud',
            field=models.CharField(max_length=25),
        ),
    ]
